### ISSUE TITLE
No way to connect to boot2docker without inactive TLS

### ISSUE THREAD

**Issue by zepouet** [Treeptik/docker-viz#1]
➜  docker-viz git:(master) go run docker-viz.go
[GIN-debug] GET   /                         --> main.func·001 (3 handlers)
[GIN-debug] GET   /dendrogam                --> main.func·002 (3 handlers)
[GIN-debug] GET   /bubble/:name             --> main.func·003 (3 handlers)
[GIN-debug] GET   /flare/:name/json         --> main.func·004 (3 handlers)
[GIN-debug] Listening and serving HTTP on :8080
[GIN] 2015/04/24 - 10:20:18 | 200 |    709.722µs | [::1]:63143 |   GET     /
[GIN] 2015/04/24 - 10:20:20 | 200 |    914.829µs | [::1]:63143 |   GET     /dendrogam
2015/04/24 10:20:25 Get http://192.168.59.104:2376/v1.15/images/json: malformed HTTP response "\x15\x03\x01\x00\x02\x02". Are you trying to connect to a TLS-enabled daemon without TLS?
exit status 1

**Comment by Xawirses** [comment]
https://github.com/samalba/dockerclient/issues/59
